# change the followings to match your Github username and repo name
baseurl: "/ESP32-Boards" # the name of your github repo
url: "https://androidcrypto.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "ESP32-Boards Overview"
description: An overview about my ESP32-Family boards from a developers view

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: AndroidCrypto (Michael Fehr)
author-bio: Hobbyist
author-image: 279.png  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: ESP32
  permalink: esp32
- text: ESP32-S3
  permalink: esp32_s3
- text: ESP32 Mini
  permalink: esp32_mini  
- text: About
  permalink: about

# use false to turn off any social media links
twitter: false
facebook: https://facebook.com/
instagram: https://instagram.com/
github: https://github.com/androidcrypto/
linkedin: https://linkedin.com/
medium: false
google-scholar: false
email: false

# footer information
footer-msg: "Powered by Tailpages"
footer-msg-link: https://github.com/harrywang/tailpages

# google analytics
google-analytics: false

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag





